name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Node.js
    uses: cnpm/github-actions/.github/workflows/node-release.yml@master
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
